baseurl:        /

source:         .
destination:    ./_site
plugins:        ./_plugins

pygments:       true
markdown:       kramdown
permalink:      date

kramdown:
    auto_ids: true,
    footnote_nr: 1